import type { EnemyStatsMap } from '../../game/enemies/types';

export const LEVEL_1_ENEMIES = {
  snail: {
    speed: 72,
    scale: 1.15,
    yOffset: -18,
    attackRange: 24,
    idleAnim: 'snail-walk',
    runAnim: 'snail-walk',
    attackAnim: 'snail-attack',
    attackDuration: 280,
    facesLeftByDefault: true,
    hpBarOffsetY: 36,
    spawnGrace: 1200,
  },
  bee: {
    speed: 95,
    scale: 1.0,
    yOffset: -70,
    attackRange: 34,
    idleAnim: 'bee-fly',
    runAnim: 'bee-fly',
    attackAnim: 'bee-attack',
    attackDuration: 320,
    facesLeftByDefault: true,
    hpBarOffsetY: 46,
    spawnGrace: 1400,
  },
  boar: {
    speed: 96,
    scale: 1.58,
    yOffset: -20,
    attackRange: 44,
    idleAnim: 'boar-idle',
    runAnim: 'boar-run',
    attackAnim: 'boar-attack',
    attackDuration: 300,
    facesLeftByDefault: true,
    hpBarOffsetY: 44,
    spawnGrace: 1300,
  },
  alphaBoar: {
    speed: 118,
    scale: 2.05,
    yOffset: -22,
    attackRange: 58,
    idleAnim: 'alpha-boar-idle',
    runAnim: 'alpha-boar-run',
    attackAnim: 'alpha-boar-attack',
    attackDuration: 360,
    facesLeftByDefault: true,
    hpBarOffsetY: 55,
    spawnGrace: 1200,
  },
} satisfies EnemyStatsMap;
