import type { EnemyStatsMap } from "../../game/enemies/types";

export const LEVEL_2_ENEMIES = {
  skeleton: {
    speed: 112,
    scale: 1.32,
    yOffset: -18,
    attackRange: 42,
    idleAnim: "skeleton-idle",
    runAnim: "skeleton-walk",
    attackAnim: "skeleton-attack",
    hurtAnim: "skeleton-hurt",
    deathAnim: "skeleton-die",
    attackDuration: 360,
    facesLeftByDefault: false,
    hpBarOffsetY: 58,
    spawnGrace: 900,
  },
  bat: {
    speed: 142,
    scale: 1.18,
    yOffset: -76,
    attackRange: 40,
    idleAnim: "bat-idle",
    runAnim: "bat-run",
    attackAnim: "bat-attack",
    hurtAnim: "bat-hurt",
    deathAnim: "bat-die",
    attackDuration: 320,
    facesLeftByDefault: true,
    hpBarOffsetY: 52,
    spawnGrace: 850,
  },
  deathBringer: {
    speed: 78,
    scale: 1.60,
    yOffset: -18,

    attackRange: 36,

    idleAnim: "death-bringer-idle",
    runAnim: "death-bringer-walk",
    attackAnim: "death-bringer-attack",
    castAnim: "death-bringer-cast",
    specialAnim: "death-bringer-spell",
    hurtAnim: "death-bringer-hurt",
    deathAnim: "death-bringer-death",
    attackDuration: 480,
    attackHitDelay: 150,
    damage: 0.7,
    facesLeftByDefault: true,
    hpBarOffsetY: 98,
    spawnGrace: 500,
  },
} satisfies EnemyStatsMap;
